<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ScreenCapture</AssemblyName><RootNamespace>SdrCapture</RootNamespace><PathMap>$(MSBuildProjectDirectory)=/_/ScreenCapture/src</PathMap><RepositoryUrl>https://github.com/Aleksei-Melnik/ScreenCapture</RepositoryUrl><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PlatformTarget>x64</PlatformTarget>
    <Version>0.7.1</Version><AssemblyVersion>0.7.1.0</AssemblyVersion><FileVersion>0.7.1.0</FileVersion>
    <ApplicationIcon>Assets\SdrCapture.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Vortice.Direct3D11" Version="3.8.3" /><PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="Assets\SdrCapture.ico" LogicalName="SdrCapture.AppIcon.ico" /></ItemGroup>
  <ItemGroup><PackageReference Include="NAudio.Wasapi" Version="2.3.0" /></ItemGroup>
  <ItemGroup><EmbeddedResource Include="Assets\release-public.pem" LogicalName="SdrCapture.ReleasePublicKey" /></ItemGroup>
</Project>
